* code working => rotate in 1D
* use 2D to train model
* normalise everything (to have equal weight)
* read about CNN => interprete the filters
* calculate correlation function (not for all functions)
* not use all lambdas => use in between to check
* Q ~ $\frac{2\pi}{l}$, q ~ $ \lambda_0$ => inelastic scattering

In [1]:
#Should be version 3.6.9
from platform import python_version
print('Currently using Python',python_version())

Currently using Python 3.6.9


In [2]:
#importing libraries
import h5py
import numpy as np
import matplotlib.pyplot as plt
import sys
import source_code as sc

#path to the datafile
hdf5_path = 'data/dataset.hdf5'

dir(sc)[:6]

['AnalyseSimulation',
 'GetHydroSamples',
 'GetRandomSamples',
 'MultipleAnalysis',
 'ReadFile',
 'TwoDimHeatmap']

In [12]:
with h5py.File(hdf5_path) as file:
    x_test = file['test_data'][:,:,:,:,:]
    y_test = file['test_labels'][:]

In [15]:
x_test.shape

(6400, 32, 32, 32, 3)

In [7]:
def Scale(x_train,x_test):
    '''
    Scales the x_train and x_test with the mean and std from x_train
    '''
    avr = np.mean(x_train,axis=(0,1,2,3))
    std = np.std(x_train,axis=(0,1,2,3))
    
    x_train_scaled = (x_train - avr)/std
    x_test_scaled = (x_test - avr)/std
    
    return x_train_scaled,x_test_scaled
    

In [3]:
x_train, y_train, x_test, y_test = sc.ReadFile(hdf5_path)

In [5]:
x_test.shape

(6400, 32, 32, 32, 3)

In [8]:
x_train,x_test=Scale(x_train,x_test)

In [9]:
np.mean(x_train,axis=(0,1,2,3))

array([0.16103153, 0.16      , 0.16006407], dtype=float32)

In [ ]:
#approx. memory usage of x_train
sys.getsizeof(x_train)

In [18]:
x_train[1,1,1,1]

array([0.968319, 0.65625 , 0.553979], dtype=float32)

In [20]:
x_train[1].shape

(32, 32, 32, 3)

In [40]:
print(x_train[0,:,:,:,:])

[[[[0.883221 0.653637 0.507404]
   [0.932422 0.640389 0.517046]
   [1.12244  0.651724 0.509694]
   ...
   [1.0514   0.657913 0.50797 ]
   [1.12379  0.649349 0.517072]
   [0.947242 0.664343 0.509494]]

  [[1.11682  0.655344 0.515222]
   [1.01879  0.656548 0.512943]
   [1.0339   0.66199  0.516182]
   ...
   [1.0629   0.63873  0.527929]
   [1.02317  0.660036 0.516605]
   [1.29788  0.656744 0.50664 ]]

  [[1.69197  0.645481 0.524045]
   [0.705046 0.675806 0.513887]
   [0.808221 0.652074 0.518759]
   ...
   [1.5191   0.642539 0.510522]
   [1.37042  0.672431 0.520348]
   [1.10424  0.656751 0.538646]]

  ...

  [[1.07191  0.662945 0.518049]
   [1.07667  0.655617 0.509646]
   [1.38391  0.647233 0.511643]
   ...
   [0.915251 0.656467 0.517924]
   [1.15916  0.643771 0.513353]
   [0.720803 0.678381 0.521657]]

  [[0.53089  0.665979 0.508634]
   [1.04205  0.668169 0.509119]
   [1.02827  0.65276  0.51368 ]
   ...
   [0.861812 0.660365 0.515011]
   [0.990281 0.660752 0.514587]
   [0.900204 0.64773  